/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import clases.Area;
import clases.Asignatura;
import clases.Docente;
import clases.Grado;
import clases.Jornada;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;  
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
//import listaGenericaArreglo.Lista;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utiles.Rut;

/**
 *
 * @author folke
 */
public class FrmConsultas extends javax.swing.JFrame {
    private ArrayList<Docente> docentes = new ArrayList();
    private ArrayList<Asignatura> asignaturas = new ArrayList();

    /**
     * Creates new form FrmConsultas
     */
    public FrmConsultas() {
        initComponents();
        this.setSize(630, 560);
        this.setLocationRelativeTo(null);
        this.cboAreas.setModel(new DefaultComboBoxModel(Area.values()));
        this.cboGrados.setModel(new DefaultComboBoxModel(Grado.values()));
        generarComboDocentes("docentes.txt");
        generarComboHorarios("horarios.txt");
        generarComboSalas("salas.txt");
        generarComboTitulos("docentes.txt");
        generarDocentes("docentes.txt");
        generarAsignaturas("asignaturas.txt");       
    }
    
    public void generarComboDocentes(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String linea;
            String nombre;
            
            while(sc.hasNextLine()){
                linea = sc.nextLine();
                String[] campos = linea.split(",");
                nombre = campos[1];
                this.cboDocentes.addItem(nombre);
            }
            sc.close();
            f.close();
        }
        catch(IOException ex){
            
        }
    }
    
    public void generarComboHorarios(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String horario;
            
            while(sc.hasNextLine()){
                horario = sc.nextLine();
                this.cboHorarios.addItem(horario);
            }
            sc.close();
            f.close();
        }
        catch(IOException ex){
            
        }
    }
    
    public void generarComboSalas(String archivo){
        try{
            FileReader f = new FileReader(archivo); 
            Scanner sc = new Scanner(f);
            String sala;
            
            while(sc.hasNextLine()){
                sala = sc.nextLine();
                this.cboSalas.addItem(sala);
            }
            sc.close();
            f.close();
        }
        catch(IOException ex){
            
        }
    }
    
    public void generarComboTitulos(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String linea;
            String titulo;
            
            while(sc.hasNextLine()){
                linea = sc.nextLine();
                String[] campos = linea.split(",");
                titulo = campos[2];
                this.cboTitulos.addItem(titulo);
            }
            sc.close();
            f.close();
        }
        catch(IOException ex){
            
        }
    }
    
    public void generarDocentes(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String linea;
            
            while(sc.hasNextLine()){
                linea = sc.nextLine();
                Docente d = new Docente(linea);
                docentes.add(d);
            }
            sc.close();
            f.close();
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }
    
    public void generarAsignaturas(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String linea;
            
            while(sc.hasNextLine()){
                linea = sc.nextLine();
                Asignatura a = new Asignatura(linea);
                asignaturas.add(a);
            }
            sc.close();
            f.close();
            
        } 
        catch (IOException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cboSalas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboAreas = new javax.swing.JComboBox<>();
        cboDocentes = new javax.swing.JComboBox<>();
        cboHorarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsultas = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboGrados = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboTitulos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 40);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUSCAR ASIGNATURAS");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 70, 180, 17);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(300, 50, 10, 220);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BUSCAR DOCENTES");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 70, 180, 17);

        cboSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSalasActionPerformed(evt);
            }
        });
        getContentPane().add(cboSalas);
        cboSalas.setBounds(410, 210, 130, 30);

        jLabel4.setText("Docentes:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 120, 70, 16);

        jLabel5.setText("Horarios:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 170, 60, 16);

        jLabel6.setText("Salas:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 220, 36, 16);

        jLabel7.setText("Titulos:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 220, 50, 16);

        cboAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreasActionPerformed(evt);
            }
        });
        getContentPane().add(cboAreas);
        cboAreas.setBounds(100, 110, 130, 30);

        cboDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDocentesActionPerformed(evt);
            }
        });
        getContentPane().add(cboDocentes);
        cboDocentes.setBounds(410, 110, 130, 30);

        cboHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHorariosActionPerformed(evt);
            }
        });
        getContentPane().add(cboHorarios);
        cboHorarios.setBounds(410, 160, 130, 30);

        txtConsultas.setColumns(20);
        txtConsultas.setRows(5);
        jScrollPane1.setViewportView(txtConsultas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 590, 180);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(10, 480, 69, 25);

        jLabel8.setText("Areas:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 120, 38, 16);

        cboGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGradosActionPerformed(evt);
            }
        });
        getContentPane().add(cboGrados);
        cboGrados.setBounds(100, 160, 130, 30);

        jLabel9.setText("Grados:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 170, 50, 16);

        cboTitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTitulosActionPerformed(evt);
            }
        });
        getContentPane().add(cboTitulos);
        cboTitulos.setBounds(100, 210, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreasActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String areaCombo = this.cboAreas.getSelectedItem().toString();
        String areaLista; 
        
        for (int i = 0; i < docentes.size(); i++){
            areaLista = docentes.get(i).getArea().toString();
            if (areaCombo.compareTo(areaLista) == 0){
                this.txtConsultas.append(docentes.get(i).toString() + "\n"); 
            }
        }
    }//GEN-LAST:event_cboAreasActionPerformed

    private void cboDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDocentesActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String docenteCombo = this.cboDocentes.getSelectedItem().toString();
        String docenteLista;
        
        for (int i = 0; i < asignaturas.size(); i++){
            docenteLista = asignaturas.get(i).getDocente().toString();
            if (docenteCombo.compareTo(docenteLista) == 0){
                this.txtConsultas.append(asignaturas.get(i).toString() + "\n");
            }
        }
    }//GEN-LAST:event_cboDocentesActionPerformed

    private void cboHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHorariosActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String horarioCombo = this.cboHorarios.getSelectedItem().toString();
        String horarioLista;
        
        for (int i = 0; i < asignaturas.size(); i++){
            horarioLista = asignaturas.get(i).getHorario().toString();
            if (horarioCombo.compareTo(horarioLista) == 0){
                this.txtConsultas.append(asignaturas.get(i).toString() + "\n");
            }
        }
    }//GEN-LAST:event_cboHorariosActionPerformed

    private void cboSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSalasActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String salaCombo = this.cboSalas.getSelectedItem().toString();
        String salaLista;
        
        for (int i = 0; i < asignaturas.size(); i++){
            salaLista = asignaturas.get(i).getSala().toString();
            if (salaCombo.compareTo(salaLista) == 0){
                this.txtConsultas.append(asignaturas.get(i).toString() + "\n");
            }
        }
    }//GEN-LAST:event_cboSalasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cboGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGradosActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String gradoCombo = this.cboGrados.getSelectedItem().toString();
        String gradoLista;
        
        for (int i = 0; i < docentes.size(); i++){
            gradoLista = docentes.get(i).getGradoAcademico().toString();
            if (gradoCombo == gradoLista){
                this.txtConsultas.append(docentes.get(i).toString() + "\n");
            }
        }
    }//GEN-LAST:event_cboGradosActionPerformed

    private void cboTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTitulosActionPerformed
        // TODO add your handling code here:
        this.txtConsultas.setText(null);
        String tituloCombo = this.cboTitulos.getSelectedItem().toString();
        String tituloLista;
        
        for (int i = 0; i < docentes.size(); i++){
            tituloLista = docentes.get(i).getTitulo().toString();
            if (tituloCombo.compareTo(tituloLista) == 0){
                this.txtConsultas.append(docentes.get(i).toString() + "\n"); 
            }
        }
    }//GEN-LAST:event_cboTitulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cboAreas;
    private javax.swing.JComboBox<String> cboDocentes;
    private javax.swing.JComboBox<String> cboGrados;
    private javax.swing.JComboBox<String> cboHorarios;
    private javax.swing.JComboBox<String> cboSalas;
    private javax.swing.JComboBox<String> cboTitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtConsultas;
    // End of variables declaration//GEN-END:variables
}
