/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

/**
 *
 * @author folke
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistro = new javax.swing.JMenu();
        subDocente = new javax.swing.JMenuItem();
        subAsignatura = new javax.swing.JMenuItem();
        subAsignar = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        subDocentes = new javax.swing.JMenuItem();
        subConsultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mnuRegistro.setText("Registro");

        subDocente.setText("Docentes");
        subDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDocenteActionPerformed(evt);
            }
        });
        mnuRegistro.add(subDocente);

        subAsignatura.setText("Asignatura");
        subAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAsignaturaActionPerformed(evt);
            }
        });
        mnuRegistro.add(subAsignatura);

        subAsignar.setText("Horarios y Salas");
        subAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAsignarActionPerformed(evt);
            }
        });
        mnuRegistro.add(subAsignar);

        jMenuBar1.add(mnuRegistro);

        mnuConsultas.setText("Consultas");

        subDocentes.setText("Docentes");
        subDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDocentesActionPerformed(evt);
            }
        });
        mnuConsultas.add(subDocentes);

        subConsultas.setText("Otras Consultas");
        subConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subConsultasActionPerformed(evt);
            }
        });
        mnuConsultas.add(subConsultas);

        jMenuBar1.add(mnuConsultas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDocentesActionPerformed
        // TODO add your handling code here:
        FrmListaDocentes f = new FrmListaDocentes();
        f.setVisible(true);
    }//GEN-LAST:event_subDocentesActionPerformed

    private void subDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDocenteActionPerformed
        // TODO add your handling code here:
        FrmRegistrarDocente f = new FrmRegistrarDocente();
        f.setVisible(true);
    }//GEN-LAST:event_subDocenteActionPerformed

    private void subAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAsignaturaActionPerformed
        // TODO add your handling code here:
        FrmRegistrarAsignatura f = new FrmRegistrarAsignatura();
        f.setVisible(true);
    }//GEN-LAST:event_subAsignaturaActionPerformed

    private void subAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAsignarActionPerformed
        // TODO add your handling code here:
        FrmRegistrarHorarioSala f = new FrmRegistrarHorarioSala();
        f.setVisible(true);
    }//GEN-LAST:event_subAsignarActionPerformed

    private void subConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subConsultasActionPerformed
        // TODO add your handling code here:
        FrmConsultas f = new FrmConsultas();
        f.setVisible(true);
    }//GEN-LAST:event_subConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenuItem subAsignar;
    private javax.swing.JMenuItem subAsignatura;
    private javax.swing.JMenuItem subConsultas;
    private javax.swing.JMenuItem subDocente;
    private javax.swing.JMenuItem subDocentes;
    // End of variables declaration//GEN-END:variables
}
