/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import clases.Area; 
import clases.Docente;
import clases.Grado;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import listaGenericaArreglo.Lista;
import utiles.Rut;

/**
 *
 * @author folke
 */
public class FrmRegistrarDocente extends javax.swing.JFrame {
    private ArrayList<Docente> docentes = new ArrayList();
    /**
     * Creates new form FrmRegistrarDocente
     */
    public FrmRegistrarDocente() {
        initComponents();
        this.setSize(550, 400);
        this.setLocationRelativeTo(null);
        this.cboArea.setModel(new DefaultComboBoxModel(Area.values())); //fill a combobox with enum values
        this.cboGrado.setModel(new DefaultComboBoxModel(Grado.values()));
        generarDocentes("docentes.txt");
    }   
    
    public void generarDocentes(String archivo){
        try{
            FileReader f = new FileReader(archivo);
            Scanner sc = new Scanner(f);
            String linea;
            
            while(sc.hasNextLine()){
                linea = sc.nextLine();
                Docente d = new Docente(linea);
                docentes.add(d);
            }
            sc.close();
            f.close();
            
        } 
        catch (IOException ex) {
            
        }
    }
    
    public boolean expresionesRegulares(){
        
        boolean valido = false;
        //Pattern pRut = Pattern.compile("([0-9]{8}-[0-9]{1})|([0-9]{8}-[K-k])$");
        Pattern pRut = Pattern.compile("([0-9]{8}-[0-9]{1})");
        Matcher mRut = pRut.matcher(txtRut.getText());
        boolean rutValido = mRut.matches();
        Pattern pNombre = Pattern.compile("([A-Za-z]+ [A-Za-z]+)$");
        Matcher mNombre = pNombre.matcher(txtNombre.getText());
        boolean nombreValido = mNombre.matches();
        Pattern pTitulo = Pattern.compile("([A-Za-z]+)$");
        Matcher mTitulo = pTitulo.matcher(txtTitulo.getText());
        boolean tituloValido = mTitulo.matches();
        
        if(txtRut.getText() == null || rutValido == false){
            JOptionPane.showMessageDialog(this, "RUT invalido");
            this.txtRut.requestFocus();
            valido = false;
        }
        else if(txtNombre.getText() == null || nombreValido == false){
            JOptionPane.showMessageDialog(this, "Nombre invalido");
            this.txtNombre.requestFocus();
            valido = false;
        }
        else if(txtTitulo.getText() == null || tituloValido == false){
            JOptionPane.showMessageDialog(this, "Titulo invalido");
            this.txtTitulo.requestFocus();
            valido = false;
        }
        else{
            valido = true;
        }
        return valido;
    }
    
    public boolean docenteExiste(){
        boolean existe = false;
        String txtRut = this.txtRut.getText();
        String rut;
        
        for(int i = 0; i < docentes.size(); i++){
            rut = docentes.get(i).getRutDocente().toString();
            if(txtRut.compareTo(rut) == 0){
                existe = true;
                JOptionPane.showMessageDialog(this, "Docente ya esta registrado");
            }
        }
        return existe  ;     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        cboGrado = new javax.swing.JComboBox<>();
        cboArea = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR DOCENTE");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 40);

        jLabel3.setText("Grado Academico:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 110, 16);

        jLabel4.setText("RUT:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 29, 16);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(190, 150, 110, 30);

        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 120, 50, 16);

        jLabel6.setText("Titulo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 37, 16);

        jLabel7.setText("Area:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 200, 50, 16);
        getContentPane().add(txtRut);
        txtRut.setBounds(190, 70, 110, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(190, 110, 110, 30);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(390, 180, 80, 25);

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1);
        btnGuardar1.setBounds(390, 140, 79, 25);

        getContentPane().add(cboGrado);
        cboGrado.setBounds(190, 230, 110, 30);

        cboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreaActionPerformed(evt);
            }
        });
        getContentPane().add(cboArea);
        cboArea.setBounds(190, 190, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboAreaActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        if (expresionesRegulares() == true && docenteExiste() == false){
            Rut rut = new Rut(txtRut.getText());
            if (rut.esValido()){
                Docente d = new Docente(rut, txtNombre.getText(), txtTitulo.getText(), cboArea.getSelectedItem().toString(), cboGrado.getSelectedItem().toString());
                d.toSave("docentes.txt");
                JOptionPane.showMessageDialog(this, "Docente registrado");
            
                this.txtRut.setText(null);
                this.txtNombre.setText(null);
                this.txtTitulo.setText(null);
            }
            else{
                JOptionPane.showMessageDialog(this, "RUT invalido");
            }            
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> cboArea;
    private javax.swing.JComboBox<String> cboGrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
