/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author folke
 */
public class FrmRegistrarHorarioSala extends javax.swing.JFrame {

    /**
     * Creates new form FrmAsignarAsignatura
     */
    public FrmRegistrarHorarioSala() {
        initComponents();
        this.setSize(580, 400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarSala = new javax.swing.JButton();
        btnRegistrarHorario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR HORARIOS Y SALAS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(272, 50, 10, 270);

        btnRegistrarSala.setText("Registrar");
        btnRegistrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSalaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarSala);
        btnRegistrarSala.setBounds(300, 140, 85, 25);

        btnRegistrarHorario.setText("Registrar");
        btnRegistrarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarHorario);
        btnRegistrarHorario.setBounds(20, 140, 85, 25);

        jLabel2.setText("Sala:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 80, 50, 16);

        jLabel3.setText("Horario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 50, 16);
        getContentPane().add(txtSala);
        txtSala.setBounds(360, 70, 130, 30);
        getContentPane().add(txtHorario);
        txtHorario.setBounds(90, 72, 130, 30);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(470, 300, 69, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioActionPerformed
        // TODO add your handling code here:
        Pattern p1Horario = Pattern.compile("([0-9]{1,2}:[0-5]{1}[0-9]{1}-[0-9]{1,2}:[0-5]{1}[0-9]{1})$");
        Matcher m1Horario = p1Horario.matcher(txtHorario.getText());
        boolean horario1Valido = m1Horario.matches();
        
        if (txtHorario.getText() == null || horario1Valido == false){
            JOptionPane.showMessageDialog(this, "Horario invalido");
            this.txtHorario.requestFocus();
        }
        else{
            try{
                FileWriter f = new FileWriter("horarios.txt", true);
                PrintWriter p = new PrintWriter(f);
                p.println(txtHorario.getText());
                p.close();
                f.close();
                JOptionPane.showMessageDialog(this, "Horario registrado");
                this.txtHorario.setText(null);
            }
            catch(IOException ex){
                
            }
        }
    }//GEN-LAST:event_btnRegistrarHorarioActionPerformed

    private void btnRegistrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSalaActionPerformed
        // TODO add your handling code here:
        Pattern pSala = Pattern.compile("([A-Za-z]{3}-[0-9]{3})$");
        Matcher mSala = pSala.matcher(txtSala.getText());
        boolean salaValido = mSala.matches();
        
        if (txtSala.getText() == null || salaValido == false){
            JOptionPane.showMessageDialog(this, "Sala invalido");
            this.txtSala.requestFocus();
        }
        else{
            try{
                FileWriter f = new FileWriter("salas.txt", true);
                PrintWriter p = new PrintWriter(f);
                p.println(txtSala.getText());
                p.close();
                f.close();
                JOptionPane.showMessageDialog(this, "Sala registrado");
                this.txtSala.setText(null);
            }
            catch(IOException ex){
                
            }
        }
    }//GEN-LAST:event_btnRegistrarSalaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarHorarioSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarHorarioSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarHorarioSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarHorarioSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarHorarioSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrarHorario;
    private javax.swing.JButton btnRegistrarSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables
}
